### PR TITLE
WIP: add ValueRate and scale points by ValueRate while rebuilding

### PR DESCRIPTION
**Pull request by datbth**
## Specifications
We want to scale up/down the points that were acquired in earlier time periods in order to balance the Tinhte's point economy.  
**Example**
* Each point acquired before 2018 should worth 0.3 x value of point in current time
* Each point acquired before 2019 should worth 0.8 x value of point in current time

### Database tables
**value_rate**
* rate_id
* rate (float)
* valid_to (uint)
### Execution
When rebuilding bonuses, each point will be scaled up/down based on the time it was acquired: `scaled_point = point * value_rate`.  
Logic to determine the value_rate:
```php
// $valueRates are all value_rate records sorted by valid_to DESC
foreach ($valueRates as $valueRate) {
  if ($valueRate['valid_to'] >= $time_when_point_was_acquired) {
    return $valueRate['rate'];
  }
}
return 1;
```

### CODE REVIEW

**Comment by daohoangson** [comment]
What is the planned usage for this feature? I assume something similar to the example?

> Each point acquired before 2018 should worth 0.3 x value of point in current time
> Each point acquired before 2019 should worth 0.8 x value of point in current time

Will you adjust scale rate next year? e.g. edit the <2018 to be 0.2, <2019 to be 0.5, add <2020 to be 0.8?

You do understand add/edit/delete scale rate will require a full bonus rebuild right?

**Comment by datbth** [comment]
Yes anh. But we will only be doing these adjustments very rarely (after thorough economy analyses) so I think full rebuilds are ok

**Comment by daohoangson** [comment]
> Will you adjust scale rate next year? e.g. edit the <2018 to be 0.2, <2019 to be 0.5, add <2020 to be 0.8?

This is planned?

**Comment by datbth** [comment]
closing this to follow new approach in internal discussion

**Pull request closed without merging**
